### ISSUE TITLE
Eventsource: how to detect client disconnection in server push example

### ISSUE THREAD

**Issue by hongnguyenhuu96** [valyala/fasthttp#771] opened 2020-04-06 09:39 UTC
This is my server code
```go
package main

import (
	"bufio"
	"fmt"
	"log"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	// Start fasthttp server for streaming responses.
	if err := fasthttp.ListenAndServe(":8080", responseStreamHandler); err != nil {
		log.Fatalf("unexpected error in server: %s", err)
	}
}

func responseStreamHandler(ctx *fasthttp.RequestCtx) {
	// cors
	ctx.Response.Header.Set("Access-Control-Allow-Origin", "*")
	// header for server push
	ctx.Response.Header.Set("Content-Type", "text/event-stream")
	ctx.Response.Header.Set("Cache-Control", "no-cache")
	ctx.Response.Header.Set("Connection", "keep-alive")
	// Send the response in chunks and wait for a second between each chunk.
	notify := ctx.Done()
	ctx.SetBodyStreamWriter(func(w *bufio.Writer) {
		i := 0
		for {
			select {
			case <-notify:
				fmt.Println("connection is closed")
				return
			default:
				fmt.Fprintf(w, "event: message\ndata: this is a message number %d\n\n", i)
				// Do not forget flushing streamed data to the client.
				if err := w.Flush(); err != nil {
					return
				}
				time.Sleep(time.Second)
				i++
			}
		}
	})
}
```
this is my client code to connect
```javascript
var client = new EventSource("http://localhost:8080")

client.onmessage = (msg) => console.log(msg)
client.onopen = (e) => console.log(e)
```

When the connection is closed (by calling client.close() or close browser's tab)
I want to handle the event `close connection` but nothing is sent to the notify channel `ctx.Done()`

In `net/http` package, when the connection is close, there will be an event sent to
`req.Context().Done()` and "connection is closed" is loged
```go
package main

import (
	"fmt"
	"net/http"
	"time"
)

func main() {
	http.ListenAndServe(":8080", http.HandlerFunc(responseStreamHandler))
}

func responseStreamHandler(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "Streaming unsupported!", http.StatusInternalServerError)
		return
	}
	notify := req.Context().Done()
	i := 0
	for {
		select {
		case <-notify:
			fmt.Println("connection is closed")
			// do something here to release resouces
			return
		default:
			// do something here that hold resources
			fmt.Fprintf(w, "event: message\ndata: this is a message number %d\n\n", i)
			// Do not forget flushing streamed data to the client.
			flusher.Flush()
			time.Sleep(time.Second)
			i++
		}
	}
}
```

so ctx.Done() is not equivalent to req.Context().Done() in net/http?

**Comment by erikdubbelboer** [comment] 2020-04-06 10:16
I have never done anything like this with fasthttp before. Isn't `w.Flush()` returning an error when the connection is lost?

**Comment by hongnguyenhuu96** [comment] 2020-04-06 11:24
> I have never done anything like this with fasthttp before. Isn't `w.Flush()` returning an error when the connection is lost?

Yes, w.Flush return error `connection closed`
but in some cases, there is no call to write and flush data anymore and we still want to detect `connection closed` to release resources immediately.

I have added the code using `net/http` package. @erikdubbelboer 
I want to transform it to fasthttp

**Comment by dgrr** [comment] 2020-04-06 12:22
Maybe with this:
```go
type RequestCtx {
  after func()
  ...
}

func (ctx *RequestCtx) DoAfter(fn func()) {
  ctx.after = fn
}

func releaseCtx(...) {
  if ctx.after != nil {
    ctx.after()
  }
  ...
}
```
So in your code you can do something like:
```go
notify := make(chan struct{}, 1)
ctx.DoAfter(func() {
  close(notify)
})

ctx.SetBodyStreamWriter(func(w *bufio.Writer) {
  timer := time.NewTimer(time.Second)
  defer timer.Stop()

  for i := 0; ; i++ {
    select {
    case <-notify:
      fmt.Println("connection is closed")
      return
    case <-timer.C:
      fmt.Fprintf(w, "event: message\ndata: this is a message number %d\n\n", i)
      if err := w.Flush(); err != nil {
        return
      }
    }
  }
})
```

**Comment by erikdubbelboer** [comment] 2020-04-06 12:32
@hongnguyenhuu96 does that `net/http` code work? The problem is that you can only know if the connection is closed by trying to write to it. So if `net/http` hits that `notify` part I'm wondering how they do it, do they try to write empty packets or maybe they are reading from the connection as well an notice it that way.

**Comment by hongnguyenhuu96** [comment] 2020-04-07 05:10
> @hongnguyenhuu96 does that `net/http` code work? The problem is that you can only know if the connection is closed by trying to write to it. So if `net/http` hits that `notify` part I'm wondering how they do it, do they try to write empty packets or maybe they are reading from the connection as well an notice it that way.

Yes. It works. You can run that `net/http` code, then visit http://localhost:8080 on a browser's tab, then close the tab, the following code is run ("connection is closed" is logged)

```go
notify := req.Context().Done()
case <-notify:
	fmt.Println("connection is closed")
	// do something here to release resouces
	return
```

**Comment by erikdubbelboer** [comment] 2020-04-07 19:48
When you change the timeout to 10 seconds and kill the connection right after a message it will take 10 seconds for it to notice the connection was closed. In other words net/http will also only know if the connection is closed on the next write. But unlike fasthttp it notifies `Context().Done()` before returning an error from the flush.

I don't think we want to match fasthttp to do the same as checking the error from `w.Flush()` is basically the same and much easier.

**Comment by AntDev95** [comment] 2020-06-22 10:38
Lol, after event that connection is closed called in fasthttp.ConnState, I can write to response buffer without receiving an error in response

**Comment by erikdubbelboer** [comment] 2020-06-22 10:46
Using the response buffer after your handler has returned is obviously wrong. And the only way that StateClosed is set is after your handler has returned. So I'm not sure what you mean to say here?

**Closed** 2020-07-11 07:58 UTC

**Comment by cherrot** [comment] 2024-08-18 12:34
After the connection being closed, `w.Flush` does not immediately return an error; in my experiment, it took at least 2 seconds to receive an error.


```
 ┌───────────────────────────────────────────────────┐                                                                         
 │                   Fiber v2.52.5                   │                                                                         
 │               http://127.0.0.1:8080               │                                                                         
 │       (bound on host 0.0.0.0 and port 8080)       │                                                                         
 │                                                   │                                                                         
 │ Handlers ............. 2  Processes ........... 1 │                                                                         
 │ Prefork ....... Disabled  PID ............. 41981 │                                                                         
 └───────────────────────────────────────────────────┘                                                                         
                                                                                                                               
2024/08/18 20:29:46 Flushed 2024-08-18T20:29:46.355                                                                            
2024/08/18 20:29:47 Flushed 2024-08-18T20:29:47.356                                                                            
2024/08/18 20:29:48 Flushed 2024-08-18T20:29:48.356                                                                            
2024/08/18 20:29:49 Flushed 2024-08-18T20:29:49.356                                                                            
2024/08/18 20:29:50 Error in flush:  connection closed
```

```
curl 'http://localhost:8080/events'
data: 2024-08-18T20:29:46.355

data: 2024-08-18T20:29:47.356

^C
```

```go
package main

import (
	"bufio"
	"fmt"
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
	// "github.com/gofiber/fiber/v2/middleware/compress"
)

const format = "2006-01-02T15:04:05.999"

func main() {
	app := fiber.New()
	// app.Use(compress.New())

	// SSE endpoint
	app.Get("/events", func(c *fiber.Ctx) error {
		c.Set("Content-Type", "text/event-stream")
		c.Set("Cache-Control", "no-cache")
		c.Set("Connection", "keep-alive")

		c.Context().SetBodyStreamWriter(func(w *bufio.Writer) {
			ticker := time.NewTicker(time.Second)
			defer ticker.Stop()

			t := time.Now().Format(format)
			fmt.Fprintf(w, "data: %s\n\n", t)
			w.Flush()
			log.Printf("Flushed %s\n", t)

			for tick := range ticker.C {
				t = tick.Format(format)
				_, _ = fmt.Fprintf(w, "data: %s\n\n", t)
				if err := w.Flush(); err != nil {
					log.Println("Error in flush: ", err)
					return
				}
				log.Printf("Flushed %s\n", t)
			}
		})

		return nil
	})

	log.Fatal(app.Listen(":8080"))
}
```
