### ISSUE TITLE
error when reading request headers: read tcp4 172.19.0.3:8080->172.19.0.2:37276: i/o timeout

### ISSUE THREAD

**Issue by ergoz** [valyala/fasthttp#465] opened 2018-11-15 21:05 UTC
I made a docker container with fasthttp application with fasthttp/router
```golang
......
	mrouter := router.New()
	indhdlr := indexHandler{pkgs: app.sortedPkgsList, config: app.config}
	mrouter.GET("/", baseWrapper(indhdlr.IndexPageHandler))

	app.server = &fasthttp.Server{
		Handler:      mrouter.Handler,
		Name:         serverVersion,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		// MaxConnsPerIP:        500,
		// MaxRequestsPerConn:   500,
		// MaxKeepaliveDuration:  60 * time.Second,
		TCPKeepalive:          false,
		LogAllErrors:          true,
		NoDefaultServerHeader: true,
		NoDefaultContentType:  true,
		Logger:                app.logger,
	}

	listenErr := make(chan error, 1)

	go func() {
		listenErr <- app.server.ListenAndServe(app.config.SystemListenPort)
	}()
......
```

and i have a traefik docker container, that have this fasthttp app as backend
If i open a page, it works, but sometimes it gives me "Error when parsing request in browser", and i cant find dependency for everything. And if i check logs of both containers i see this errors:

Container with fasthttp app (172.19.0.3)
```
time="2018-11-15T19:23:34.68939149Z" level=info msg="error when serving connection \"172.19.0.3:8080\"<->\"172.19.0.2:37276\": error when reading request headers: read tcp4 172.19.0.3:8080->172.19.0.2:37276: i/o timeout" func="github.com/valyala/fasthttp.(*workerPool).workerFunc" file="/go/pkg/mod/github.com/valyala/fasthttp@v1.0.0/workerpool.go:218"
```

Container with traefik (172.19.0.2)
```
2018/11/15 19:23:34 transport.go:1792: Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nDate: Thu, 15 Nov 2018 19:23:33 GMT\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 26\r\nConnection: close\r\n\r\nError when parsing request"; err=<nil>
```

And if i change read and write timeous its changes how often i get this error. As i understand is traefik opens connection and not closing it and that is why i receives this error? (but i still not understand why i get this error in browser when i not use  traefik and send request directly to application) how can i fix it? Where i am wrong?

sorry for my bad English, it is not native for me :)

**Comment by erikdubbelboer** [comment] 2018-11-16 18:05
I'm working on a fix for this. The issue is that after `ReadTimeout` instead of gracefully terminating the keep-alive connection fasthttp sends back a HTTP response with the `Error when parsing request` message. traefik obviously doesn't expect this response on an idle connection and prints the error.

The fix isn't very easy as the server needs to know if it's a timeout reading from an idle connection of if it's for example a timeout reading a request body that is taking too long.

I'll probably have a fix within the next two days.

**Comment by ergoz** [comment] 2018-11-16 19:08
Oh! It is great!!! Big thanks! It will be awesome. If you will need help
with test let me know.

пт, 16 нояб. 2018 г., 21:06 Erik Dubbelboer notifications@github.com:

**Comment by erikdubbelboer** [comment] 2018-11-21 07:04
This should be fixed now with https://github.com/valyala/fasthttp/commit/598a52272abafde3c5bebd7cc1972d3bead7a1f7

**Closed** 2018-11-21 07:03 UTC

**Comment by goith** [comment] 2018-12-14 06:21
@erikdubbelboer  encounter  a problem #491
