### ISSUE TITLE
Why not semver?

### ISSUE THREAD

**Issue by bernardolm** [valyala/fasthttp#335] opened 2018-04-05 02:16 UTC
Hello, Aliaksandr! Congratulations for this project!

One question, why you don't use [semver](https://semver.org/)? 
This can help who uses godep, dep or others.

**Comment by ybbus** [comment] 2018-05-07 11:19
Also would like to see semver.

**Comment by erikdubbelboer** [comment] 2018-08-30 15:51
Duplicate of https://github.com/valyala/fasthttp/issues/268

**Closed by erikdubbelboer** 2018-08-30 15:51 UTC
