### ISSUE TITLE
[Feature Request] Need hooks with context

### ISSUE THREAD

**Issue by vijayviji** [valyala/fasthttp#497] opened 2018-12-18 02:03 UTC
Currently, fasthttp is taking hooks for connection change, however, to track a specific request across the hooks, we need ctx as well.

This is especially useful in case of measuring latency across different connection state changes.

**Comment by erikdubbelboer** [comment] 2018-12-18 11:08
fasthttp implements [the same ConnState functionality as `net/http`](https://golang.org/pkg/net/http/#ConnState). What do you mean with the ctx?

**Comment by erikdubbelboer** [comment] 2018-12-19 10:10
The problem is that most of the state changes are done when no context is assigned to the connection and each time a new request arrives on the same connection it will have a whole new fresh context so you won't be able to use that.

What would be possible is to assign a connection ID (number) to each connection. This already happens. And then we can pass this connection ID to the `ConnState` function so you can keep a map of information per connection. Would this work for you?

**Comment by vijayviji** [comment] 2018-12-19 19:00
Yes, that would help.

**Closed** 2019-08-18 09:30 UTC
Labels: enhancement
