### ISSUE TITLE
Server shutdown fail

### ISSUE THREAD

**Issue by zc2638** [valyala/fasthttp#1327] opened 2022-06-24 09:05 UTC
When the server accepts the request, calling shutdown will permanently fail to exit.

Here is my test code.
```golang
	wg, ctx := errgroup.WithContext(context.Background())
	wg.Go(func() error {
		ch := make(chan os.Signal, 1)
		signal.Notify(ch, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGINT)
		select {
		case <-ctx.Done():
			return nil
		case sig := <-ch:
			return fmt.Errorf("server shutdown: %v", sig)
		}
	})
	s := &fasthttp.Server{Handler: r.Handler}
	wg.Go(func() error {
		return s.ListenAndServe(":8080")
	})
	wg.Go(func() error {
		<-ctx.Done()
		return s.Shutdown()
	})
	log.Fatal(wg.Wait())
```

I have the same problem as this issue #1190.
But I waited longer, and probably forever.

I found that I have a request stuck in this method, do you have any insight?
ref: https://github.com/valyala/fasthttp/blob/master/server.go#L2125

**Comment by erikdubbelboer** [comment] 2022-06-25 06:57
Which version of fasthttp are you using? I don't see (yet) how an idle connection could be hanging there without `closeIdleConns()` closing it when you call `Shutdown()`.

**Comment by zc2638** [comment] 2022-06-25 07:17
fasthttp: `v1.37.0`  
go: `1.18.3`  
os: `darwin`

In my use it is very easy to reproduce.  
you can try:  
1. Start the server
2. Make a request call from the browser
3. CTRL + C to exit the server

**Comment by erikdubbelboer** [comment] 2022-06-26 08:56
What is your handler doing? I can't seem to reproduce this. Here is a self containing example where you can wait a second for a keep-alive connection to be spawned. When you then Ctrl+C the server it kills this connection and stops normally:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/valyala/fasthttp"
	"golang.org/x/sync/errgroup"
)

func main() {
	go func() {
		time.Sleep(time.Second)

		if _, err := http.Get("http://localhost:8081/"); err != nil {
			panic(err)
		}
		fmt.Println("keep-alive connection established")
	}()

	s := &fasthttp.Server{Handler: func(ctx *fasthttp.RequestCtx) {
		ctx.WriteString("Hello, world!")
	}}

	wg, ctx := errgroup.WithContext(context.Background())
	wg.Go(func() error {
		ch := make(chan os.Signal, 1)
		signal.Notify(ch, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGINT)
		select {
		case <-ctx.Done():
			return nil
		case sig := <-ch:
			fmt.Println("\nopen connections: ", s.GetOpenConnectionsCount())

			return fmt.Errorf("server shutdown: %v", sig)
		}
	})
	wg.Go(func() error {
		return s.ListenAndServe(":8081")
	})
	wg.Go(func() error {
		<-ctx.Done()
		return s.Shutdown()
	})
	log.Fatal(wg.Wait())
}
```

**Comment by zc2638** [comment] 2022-06-27 01:25
yes, this is working fine.  
If you use a browser to access the address directly, it will reproduce.
@erikdubbelboer

**Comment by erikdubbelboer** [comment] 2022-06-27 07:58
I can't reproduce that. When I open my code above, and then request it in both Firefox and Chome. And then Ctrl+c it shows that all still have keep-alive connections, but they are all immediately killed by the Shutdown():
```sh
% go run main.go 
keep-alive connection established
^C
open connections:  3
2022/06/27 09:57:20 server shutdown: interrupt
exit status 1
```

**Comment by zc2638** [comment] 2022-06-27 08:28
[screen-recording.mov.zip](https://github.com/valyala/fasthttp/files/8990032/screen-recording.mov.zip)
I uploaded a video of my screen to see if it helps.
@erikdubbelboer

**Comment by erikdubbelboer** [comment] 2022-06-27 09:30
Can you try the same with this code? It will print more info that I could use to see what is going on on your machine:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/valyala/fasthttp"
	"golang.org/x/sync/errgroup"
)

func main() {
	go func() {
		time.Sleep(time.Second)

		if _, err := http.Get("http://localhost:8081/"); err != nil {
			panic(err)
		}
		fmt.Println("keep-alive connection established")
	}()

	s := &fasthttp.Server{Handler: func(ctx *fasthttp.RequestCtx) {
		ctx.WriteString("Hello, world!")
	}}

	go func() {
		for {
			time.Sleep(time.Second)
			fmt.Println("\nopen connections: ", s.GetOpenConnectionsCount())
			fmt.Printf("%#v\n", s)
		}
	}()

	wg, ctx := errgroup.WithContext(context.Background())
	wg.Go(func() error {
		ch := make(chan os.Signal, 1)
		signal.Notify(ch, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGINT)
		select {
		case <-ctx.Done():
			return nil
		case sig := <-ch:
			return fmt.Errorf("server shutdown: %v", sig)
		}
	})
	wg.Go(func() error {
		return s.ListenAndServe(":8081")
	})
	wg.Go(func() error {
		<-ctx.Done()
		return s.Shutdown()
	})
	log.Fatal(wg.Wait())
}
```

**Comment by zc2638** [comment] 2022-06-27 09:37
[view.txt](https://github.com/valyala/fasthttp/files/8990638/view.txt)
The logs in the process are basically here. 
Thanks.

**Comment by erikdubbelboer** [comment] 2022-06-27 09:59
Can you try with a different browser? As I can see in the logs your browser opens 2 connections, 1 that goes idle, and one that it doesn't send anything on. This second connection isn't going idle so it isn't being closed by Shudown. Do you maybe have some weird plugins on anything else that could cause this extra connection? This is not a normal thing.

In theory we could fix this by adding `StateNew` in this case statement: https://github.com/valyala/fasthttp/blob/16d30c474cea55710ff9a550f1b20b7b974053d9/server.go#L2817
This would cause new connections that we haven't received any data on to be closed as well. But this is technically incorrect as these might be requests that we are going to receive any moment and closing those would impact the user.

What you could do is set a ReadTimeout. The connection that is opened and doesn't send anything within that time is then closed.

**Comment by erikdubbelboer** [comment] 2022-06-28 09:05
I implemented the same solution net/http uses to close new connections after 5 seconds of inactivity: https://github.com/valyala/fasthttp/commit/b23c5e90838fdcb504032d8932c905ca7bd3b7ae

**Closed by erikdubbelboer** 2022-06-28 09:05 UTC
