### ISSUE TITLE
Bug with DisablePreParseMultipartForm and StreamRequestBody

### ISSUE THREAD

**Issue by im-kulikov** [valyala/fasthttp#968] opened 2021-02-12 14:18 UTC
With https://github.com/valyala/fasthttp/commit/0956208cc68009f2177e34af14d5ae766dae5734 Add request body streaming, when enabling `DisablePreParseMultipartForm` we received next error `form size must be greater than 0. Given 0`

for example

```go
func main() {
	app := &fasthttp.Server{
		Handler:            handler,
		StreamRequestBody:  true,
		DisablePreParseMultipartForm: true,
	}
	log.Fatal(app.ListenAndServe(":3000"))
}

func handler(ctx *fasthttp.RequestCtx) {
  form, err = c.MultipartForm()

  // form == nil
  // err == "form size must be greater than 0. Given 0"
}
```

**Comment by erikdubbelboer** [comment] 2021-02-12 15:15
This is a bug and I have found the cause and have a solution that I just need to test a bit more.

But I'm also curious why you would want to use `StreamRequestBody` and then immediately do `.MultipartForm()` since that will then still load the full body into memory to parse it. Or do you have multiple handlers where with some you want to use `.MultipartForm()` and with others you want to use request streaming?

**Comment by realloc** [comment] 2021-02-12 15:32
In the end, we want to be able to use a custom multipart form parser in particular cases. For example, when streaming a large file, we want to start processing the payload as is it becomes available, parsing multipart form data in a SAX-like manner.

**Comment by im-kulikov** [comment] 2021-02-12 15:33
@erikdubbelboer Thanks for a quick reply. We just need to parse the body of `multipart/form-data` on my own.

**Comment by erikdubbelboer** [comment] 2021-02-13 14:49
See: https://github.com/valyala/fasthttp/pull/970

**Comment by erikdubbelboer** [comment] 2021-02-16 20:54
I have just pushed a fix to master. I will do a new release tomorrow.

**Closed by erikdubbelboer** 2021-02-16 20:54 UTC
