### ISSUE TITLE
Cant get cookie value or get incorrect cookie value in some case. 

### ISSUE THREAD

**Issue by yajiya** [valyala/fasthttp#121] opened 2016-06-22 11:55 UTC
Cant get cookie value in some case, And I guess most because of the "=" in cookie value. Check the code please. you may switch to standard way too to try

	package main
	
	import (
		"fmt"
		"net/http"
		"time"
	
		"github.com/labstack/echo"
		"github.com/labstack/echo/engine/standard"
		//"github.com/labstack/echo/engine/fasthttp"
		"github.com/labstack/echo/middleware"
	)
	
	func main() {
	
		// Echo instance
		e := echo.New()
	
		// Middleware
		e.Use(middleware.Logger())
		e.Use(middleware.Recover())
		e.Use(middleware.Gzip())
	
		e.GET("/w", writeCookie)
		e.GET("/r", readCookie)
	
		// Start server
		e.Run(standard.New(":1323"))
	}
	
	func writeCookie(c echo.Context) error {
		cookie := new(echo.Cookie)
		cookie.SetName("sth1")
		cookie.SetPath("/")
		cookie.SetValue("MTQ2NjU5NTcwN3xfUVduVXk4aG9jSmZaNzNEb1dGa1VjekY1bG9vMmxSWlJBZUN2Q1ZtZVFNMTk2YU9YaWtCVmY1eDRWZXd3M3Q5RTJRZnZMbk5mWklSSFZJcVlXTDhiSFFHWWdpdFVLd1hwbXR2UUN4QlJ1N3BITFpkS3Y4PXzDvPNn6JVDBFB2wYVYPHdkdlZBm6n1_0QB3_GWwE40Tg==   ")
	
		cookie.SetName("sth2")
		cookie.SetPath("/")
		cookie.SetValue("123")
	
		cookie.SetName("sth3")
		cookie.SetPath("/")
		cookie.SetValue("123 ==   1")
	
		cookie.SetExpires(time.Now().AddDate(1, 0, 0))
		c.SetCookie(cookie)
		return c.String(http.StatusOK, "write a cookie")
	}
	
	func readCookie(c echo.Context) error {
	
		for _, cookie := range c.Cookies() {
			fmt.Println(cookie.Name())
			fmt.Println(cookie.Value())
		}
	
		return c.String(http.StatusOK, "read a cookie")
	}

**Comment by valyala** [comment] 2016-06-24 14:26
@yajiya , `fasthttp` allows `=` and space chars inside cookie values - see the [added test](https://github.com/valyala/fasthttp/commit/efa9cb909e6c972e779c9e4ccba2aa293809adaf) for details.

It looks like the `writeCookie` function is improperly written. It should call `c.SetCookie` after each `cookie.SetValue`, otherwise cookie is overwritten by the latest value.

**Comment by valyala** [comment] 2016-06-27 14:24
Closing the issue. @yajiya , feel free posting additional info here if the issue isn't resolved yet.

**Closed by valyala** 2016-06-27 14:24 UTC
Labels: question
