### ISSUE TITLE
Prefork w/reuse port is NOT really faster than multi-threaded

### ISSUE THREAD

**Issue by nanoant** [valyala/fasthttp#23] opened 2015-12-21 23:17 UTC
Hello I am an author of dumb & simple [WebFrameworkBenchmark](https://github.com/nanoant/WebFrameworkBenchmark). It isn't as complete as TechEmpower's one, but the purpose it just to test the framework (router) overhead.

According to your [Performance optimization tips for multi-core systems](https://github.com/valyala/fasthttp#performance-optimization-tips-for-multi-core-systems) using pre-fork with `SO_REUSEPORT` is preferred way to scale on multicore system.

However I get completely opposite numbers, when using `prefork` I get worse results (~440kreq/s) than with multi-threded simpler version (~480kreq).

You can find the source for my benchmark at:

https://github.com/nanoant/WebFrameworkBenchmark/blob/master/benchmarks/go-fasthttp/helloworldserver.go

Also another important observation is that is performance increase comparing to `net/http` is around 1.8x, and it is nowhere close to claimed 4x-10x. Thoughts?

Therefore I humbly ask you to provide some solid benchmark examples where we can see the performance differences.

**Comment by Annonomus-Penguin** [comment] 2015-12-22 02:22
Look at issue #4. He elaborates on his benchmarks and provides some of the background information behind his benchmarks.

**Comment by nanoant** [comment] 2015-12-22 10:49
@Annonomus-Penguin I have seen that. But my doubt are something else, first is preffered usage `SO_REUSEPORT` & prefork rather than normal multi-threaded. There's nothing about that in #4. Another is claim that `fasthttp` works 4x-10x than `net/http`. Again I cannot see the proof (example benchmark) for this claim.

Just to be clear, I am not denying that this solution is fast, it is VERY FAST. And it is 4th in my benchmarks, only loosing to some heavily optimized Java and 2 native C solution. So I think it is great.

**Comment by valyala** [comment] 2015-12-24 18:39
@nanoant , first of all thanks for the benchmark.

> According to your Performance optimization tips for multi-core systems using pre-fork with SO_REUSEPORT is preferred way to scale on multicore system.
> However I get completely opposite numbers, when using prefork I get worse results (~440kreq/s) than with multi-threded simpler version (~480kreq).

Prefork with SO_REUSEPORT scales perfectly when a lot of concurrent client connections (at least thouthands) are established over the real network (preferrably 10Gbit with per-CPU hardware packet queues). See #4 for details. When small number of concurrent client connections are established over localhost, then SO_REUSEPORT usually doesn't give any performance gain (like in your case).

> Also another important observation is that is performance increase comparing to net/http is around 1.8x, and it is nowhere close to claimed 4x-10x. Thoughts?

10x performance gain is achieved in synthetic benchmarks - see [server benchmark results on the main page](https://github.com/valyala/fasthttp#http-server-performance-comparison-with-nethttp). These benchmarks completely skip network API provided by the operating system - they test bare server implementation performance. In real life fasthttp is faster than net/http by up to 3x (when client uses [http pipelining](https://en.wikipedia.org/wiki/HTTP_pipelining)) due to network API overhead.

As for [the source code](https://github.com/nanoant/WebFrameworkBenchmark/blob/master/benchmarks/go-fasthttp/helloworldserver.go):

Replace

```go
io.WriteString(ctx, "Hello World")
```

with

```go
ctx.Write(helloWorldBytes)
```

where `helloWorldBytes` must be initialized in global scope as:

```go
var helloWorldBytes = []byte("Hello World")
```

This may improve benchmark performance, since it eliminates `io.WriteString` overhead.

**Comment by valyala** [comment] 2015-12-24 18:56
Just added `io.WriteString` performance booster at 80105c1a854704cb603a551ac4bc91826e92713b.  @nanoant, make `go get -u github.com/valyala/fasthttp` and re-run your tests.

**Comment by valyala** [comment] 2016-01-08 14:55
Closing this issue, since this is not a bug.

**Closed by valyala** 2016-01-08 14:55 UTC
Labels: question
