### ISSUE TITLE
Streaming request body

### ISSUE THREAD

**Issue by vincent-163** [valyala/fasthttp#622] opened 2019-08-07 10:04 UTC
Hello! First of all, thanks for the awesome work.

I'm building a simple file server that receives files from clients. The files are presented in the raw request body (i.e. no multipart/form-data), and file sizes can be several hundred megabytes large. fasthttp seems to have a small default request body limit (4MB), and when I try to increase that limit via MaxRequestBodySize I get out of memory error when uploading large files. Is there a way to stream request body directly so it uses only constant memory?

**Comment by kirillDanshin** [comment] 2019-08-07 14:57
Currently working on/testing this feature

**Comment by erikdubbelboer** [comment] 2019-08-07 15:01
At the moment not. By design fasthttp waits until the whole request is in memory before it calls the handler. @kirillDanshin is working on changing this so keep an eye on this repo.

**Comment by tsingson** [comment] 2019-08-07 17:25
> Currently working on/testing this feature

cool..........

**Comment by ochanism** [comment] 2019-12-02 07:20
@kirillDanshin Could you update your progress?

**Comment by Fenny** [comment] 2019-12-30 20:39
Any updates? Seems like a big thing

**Comment by kirillDanshin** [comment] 2019-12-30 21:08
sorry for delay.

this feature is currently in production testing. had to reimplement it again due to insufficient performance.

**Comment by erikdubbelboer** [comment] 2019-12-31 10:58
@kirillDanshin can you maybe make a pull request already (maybe in Draft mode?) so people can look at the code?

**Comment by dfirsht** [comment] 2020-02-14 21:22
@kirillDanshin any updates on this?

**Comment by johnlanni** [comment] 2020-04-08 03:42
@kirillDanshin Could you update your progress?

**Comment by dgrr** [comment] 2020-04-08 10:25
Isn't [implemented](https://github.com/valyala/fasthttp/blob/master/http.go#L1419)?
Or do you mean reading from a reader?

**Comment by Fenny** [comment] 2020-04-15 01:02
@kirillDanshin could you share what you got so far, maybe we could help?

**Comment by taoyuanyuan** [comment] 2020-04-15 04:28
@kirillDanshin could you share your code ？

**Comment by refine36** [comment] 2020-06-24 09:44
@kirillDanshin any updates on this?

**Comment by iarkaroy** [comment] 2020-08-13 18:27
@kirillDanshin any update on this?

**Comment by jan4984** [comment] 2020-12-09 09:08
any update? i use the issue-622 branch and it totally not work.  the handler blocking at 'appendBodyFixedSize'.

**Comment by dengqian** [comment] 2020-12-10 02:46
@kirillDanshin Can you maybe make a pull request already?

**Comment by kirillDanshin** [comment] 2020-12-10 04:40
@jan4984 please provide an example of this issue

**Comment by frankdvd** [comment] 2021-01-20 09:22
@kirillDanshin  Thank you so much for your work, this is a really helpful feature, any idea on when the PR will be merged?

**Closed** 2021-02-06 20:03 UTC
Labels: enhancement, pending/development
