### ISSUE TITLE
Could not peek request header cookie after `Cookie` method invoked

### ISSUE THREAD

**Issue by fate-lovely** [valyala/fasthttp#313] opened 2017-11-22 10:37 UTC
```go
// curl -H 'Cookie: name=helloworld'
func h(ctx *fasthttp.RequestCtx) {
	fmt.Println(string(ctx.Request.Header.Peek("Cookie"))) // get 'name=helloworld'
}
```

```go
// curl -H 'Cookie: name=helloworld'
func h(ctx *fasthttp.RequestCtx) {
	fmt.Println(string(ctx.Request.Header.Cookie("name"))) // get 'helloworld'
	fmt.Println(string(ctx.Request.Header.Peek("Cookie"))) // get nothing
}
```

**Comment by erikdubbelboer** [comment] 2017-11-24 02:54
The issue is that `collectCookies` (which is called by `.Cookie()`) removes the Cookie header:
https://github.com/valyala/fasthttp/blob/51bb00256c3cb0a130d470a087a98684ce003065/header.go#L1866-L1884
This can be fixed by not removing it. But then the issue is that [`VisitAll`](https://github.com/valyala/fasthttp/blob/51bb00256c3cb0a130d470a087a98684ce003065/header.go#L761) will output the Cookie header twice:
https://github.com/valyala/fasthttp/blob/51bb00256c3cb0a130d470a087a98684ce003065/header.go#L779-L784
So this code then also needs to be removed.

I don't think anyone really depends on the current behavior as it is more like a bug so I pushed a fix to my fork: https://github.com/erikdubbelboer/fasthttp

**Comment by erikdubbelboer** [comment] 2017-11-24 03:24
I could make a pull request for this but I'm afraid @valyala has shown not to be interested in fixing anything.

**Comment by fate-lovely** [comment] 2017-11-24 06:22
Thank you, I guess I should use your fork or switch to net/http, I really enjoy fasthttp design, but the maintenance seems to be a problem for such a fundamental framework.

**Comment by erikdubbelboer** [comment] 2017-11-24 06:31
That's exactly why I started my fork. It contains many bug fixes and improvements that @valyala is completely ignoring.

**Comment by illotum** [comment] 2017-11-24 21:49
Stay with us @fate-lovely! I maintain Phi fork that works on erikdubbelboer/fasthttp, can submit PR in a moment.

**Comment by tsingson** [comment] 2017-11-25 03:44
@fate-lovely  let's build more better for fasthttp ecosystem.

**Comment by erikdubbelboer** [comment] 2018-09-13 04:43
Fixed in https://github.com/valyala/fasthttp/commit/869903cf7a5ed03b91b20db48c6a555dc5bae324

**Closed by erikdubbelboer** 2018-09-13 04:43 UTC
Labels: pending/development
