### ISSUE TITLE
Thank you for fasthttp... a few questions

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#592] opened 2019-06-13 20:16 UTC
I read your code on cookie.go
1. I can't seem to find a memory maxsize value to limit the number of entries for the cookies
and I also read your code on https://github.com/victoriaMetrics/fastcache
2. the fastcache seems more appropriate to be used as cookie cache.
3. Any intent on merging the two as one to make it simpler?

thanks in advance.

**Comment by kirillDanshin** [comment] 2019-06-13 21:20
Fastcache got nothing to do with fasthttp. Fastcache is a cache made to be used inside VictoriaMetrics database.
There’s no such thing as “cookie cache”. We don’t cache cookies, as RFC doesn’t say anything about caching cookies. Also, http cookies always provided by the client, so there are no reason to cache them. Even if we would need to cache something, we can’t use fastcache because it may remove entities anytime.
Fasthttp and fastcache could not be merged because they were made to solve different problems.

**Closed by kirillDanshin** 2019-06-13 21:20 UTC

**Comment by hiqsociety** [comment] 2019-06-14 11:00
Thank you for the reply. I think I'm referring to session cookies... which is here, using cookie.go of valyala/fasthttp
https://github.com/fasthttp/session/

but hope to have a cookie session manager directly from this repo is best (and using https://github.com/victoriaMetrics/fastcache for it is better...)

ok i'll get back with the question after i re-review the code and ask at https://github.com/fasthttp/session/

hope it's merged... i mean cookie and session cookies can just be together.

**Comment by savsgio** [comment] 2019-06-14 11:39
Why do we need the fastcache to manage cookies?
The cookies only are setted/getted/removed of request/response, with fasthttp native methods.
Session has not any kind of cookies cache.

**Comment by savsgio** [comment] 2019-06-14 11:44
Adds fastcache for save the cookie id (sessionid), it's unncessary. 
Just adds complexity and not improve anything, because the session data must be recovered from backend (redis, mysql, etc)

**Comment by savsgio** [comment] 2019-06-14 11:47
Could you explain us better what do you need, please?

**Comment by savsgio** [comment] 2019-06-14 11:53
Continue here: https://github.com/fasthttp/session/issues/18

**Comment by hiqsociety** [comment] 2019-06-14 12:13
I get what u mean. I was referring to using "memory" for fasthttp/session. (which makes sense as default session cookies, and since memory, then Victoria/fastcache)

**Comment by kirillDanshin** [comment] 2019-06-14 13:17
Cookies are request-wide KV parameters that could not be cached, as I stated above.

Speaking of sessions, fasthttp does not provide built-in solution for sessions to give freedom in choosing/implementing sessions behavior. Although we provide a production-ready solution as separate package (see [github.com/fasthttp/session](https://github.com/fasthttp/session)).

Again, fastcache was not created for dealing with sessions at all, due to automatic evictions. Dealing with many sessions would constantly evict all old sessions by design. Fastcache can be used to cache such things like, e.g., video watch counts on the video page (like in youtube), post likes/views on public pages or followers count (see instagram), caching 3rd-party API responses when it's not critical to show realtime results.

Speaking of fasthttp/session, `memory` backend was made solely for testing/development purposes and should not be used for production at all. Instead, you should use other available persistent storages.

**Comment by hiqsociety** [comment] 2019-06-14 15:33
@kirillDanshin I'm writing a customized backend and thus trying to use the simplest api possible to start with and "memory" is the least complicated but thanks for the explanation, if have any other questions will post here.

**Comment by kirillDanshin** [comment] 2019-06-14 17:20
@hiqsociety when you writing any backend, you need to make it stable. Using evictable storage for sessions you will make your backend unstable and unreliable. Even memory storage in sessions doesn’t randomly evict sessions. Using fasthttp/sessions you can just setup memory backend for development and e.g. redis for persistent scaleable session storage in production. No need to use fastcache or other cache libraries here.

**Comment by savsgio** [comment] 2019-06-14 18:11
Yes, the memory backend it's only for testing/development or for very few load.
 As @kirillDanshin says, if you want an stable backend, use the others backends available in session package.

The interface complexity of backends are equal in memory as in anothers backends. So you shouldn't have difficulties to implement it in your service, just the configuration of the backend could be more difficult.

**Comment by savsgio** [comment] 2019-06-14 18:15
Before, I have been confused, because you meant about redis, not about memory, in https://github.com/fasthttp/session/issues/18 issue.
